### ISSUE TITLE
missing SDL_main functionality

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#106]
Since sdl12-compat is now providing support for building programs against
it, SDL_main functionality must be added, both for Windows and for macOS.

**Comment by icculus** [comment]
I'm assigning myself but don't have plans to do this in the next few days, in case someone else wants to grab it first.

**Comment by sezero** [comment]
As noticed in #78, an SDL_main lib is needed even for unices.

**Comment by icculus** [comment]
Initial shot at this is in 44d8d29e4f54f126a6e939db1be1bdd93c042862 ... this code is public domain in 1.2, so it's just pulling it into sdl12-compat. There's stuff we can probably delete from it (like Windows CE support or the macOS .nib file code paths), but it isn't hurting anything.

The macosx code is largely unnecessary because SDL2 handles all this stuff inside SDL_Init() now, but this stuff needs to be there if one wants to build with sdl12-compat and run with the real 1.2 on that platform, and that is useful for testing purposes if nothing else.

Windows is _completely_ untested at the moment, and might need kernel32 or something added to the link parameters.

Unix uses the "dummy" version, which in practice just makes an empty .a file.

I didn't include the code for platforms SDL2 doesn't support (qtopia, Mac OS Classic, BeOS, Symbian). BeOS can be renamed "Haiku" but I'm not in a position to work on this, so I'm inclined to omit it until a real Haiku developer wanders through later. Like macOS, I'm pretty sure this code isn't necessary on Haiku with SDL2, but is needed for real 1.2 compatibility. Unlike macOS, I don't know what sort of incompatibilities it will cause yet. We'll leave it for later.

**Comment by sezero** [comment]
Mac code has a lot of deprecations. From a build log:
```
SDLMain.m:76:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
- (void)terminate:(id)sender
^
/opt/MacOSX11.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSApplication.h:169:1: note: method 'terminate:' declared here
- (void)terminate:(nullable id)sender;
^
SDLMain.m:151:45: warning: 'NSAlternateKeyMask' is deprecated: first deprecated in macOS 10.12 [-Wdeprecated-declarations]
    [menuItem setKeyEquivalentModifierMask:(NSAlternateKeyMask|NSCommandKeyMask)];
                                            ^~~~~~~~~~~~~~~~~~
                                            NSEventModifierFlagOption
/opt/MacOSX11.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:180:35: note: 'NSAlternateKeyMask' has been explicitly marked deprecated here
static const NSEventModifierFlags NSAlternateKeyMask          API_DEPRECATED_WITH_REPLACEMENT("NSEventModifierFlagOption", macos(10.0,10.12)) = NSEventModifierFlagOption;
                                  ^
SDLMain.m:151:64: warning: 'NSCommandKeyMask' is deprecated: first deprecated in macOS 10.12 [-Wdeprecated-declarations]
    [menuItem setKeyEquivalentModifierMask:(NSAlternateKeyMask|NSCommandKeyMask)];
                                                               ^~~~~~~~~~~~~~~~
                                                               NSEventModifierFlagCommand
/opt/MacOSX11.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:181:35: note: 'NSCommandKeyMask' has been explicitly marked deprecated here
static const NSEventModifierFlags NSCommandKeyMask            API_DEPRECATED_WITH_REPLACEMENT("NSEventModifierFlagCommand", macos(10.0,10.12)) = NSEventModifierFlagCommand;
                                  ^
SDLMain.m:228:24: warning: sending 'SDLMain *' to parameter of incompatible type 'id<NSApplicationDelegate> _Nullable'
    [NSApp setDelegate:sdlMain];
                       ^~~~~~~
/opt/MacOSX11.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSApplication.h:142:54: note: passing argument to parameter 'delegate' here
@property (nullable, weak) id<NSApplicationDelegate> delegate;
                                                     ^
4 warnings generated.
```

There is also the CPS stuff, which build system won't report as deprecated
because the apis used are declared manually and the deprecation warnings
are seen at runtime - See:
https://github.com/libsdl-org/SDL-1.2/issues/775#c5

**Comment by icculus** [comment]
Starting to work on the macOS issues in a topic branch so I can see these run through the mac builder, since I won't have access to a Mac until later tonight.

The first commit should fix `category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]` ... basically they don't want you to do this sort of monkey-patching of system classes because messages can land on the wrong implementation at random...but they also forbid you from subclassing NSApplication specifically, so now this event goes to a delegate that is called by NSApplication during its `terminate` instead of trying to override `terminate` directly.

**Comment by icculus** [comment]
Okay, all deprecations are gone (including the CPS stuff where we added our own function declarations), and it still works on macOS.  :)
