### ISSUE TITLE
static builds can't be supported with windows

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#108]
Since sdl12-compat started supporting static builds as of commit 21830e8e8,
such windows builds will be in issue: The current code relies on `DllMainCRTStartup`
i.e. the library being built as a dll. The MinGW builds can be easily adjusted to use
the `dllinit` and `dllquit` constructor and destructors, but MSVC builds are an issue
if we truly want to provide static build support.

**Comment by icculus** [comment]
I say refuse to build them on anything but Linux; they are only there to satisfy a compatibility requirement of Fedora, and I'm not interested in static builds _at all_ beyond that.

Since 1.2 was LGPL, there really shouldn't be any use case where we _need_ this in general, and we can't replace 1.2 in existing statically linked binaries in any case.

**Comment by sezero** [comment]
Working on a patch.
