### ISSUE TITLE
devel option's SDL_config.h should be generated, at least for unices

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#111]
Our current SDL_config.h assumes a lot, and with the X11 headers thing
from bug #52 resulted in some ugly solution. I think we should use generated
SDL_config.h in the `devel` option, at least for unices.  Ideas?

**Comment by icculus** [comment]
I'm _really_ trying to avoid this, and maybe doing so is impossible, but I'm willing to let it remain as-is if we can survive on the __has_include magic.

There were a _lot_ of configure details in the original 1.2 headers, but almost _all_ of them can be handled with the preprocessor (byte order and pointer size checks, etc), if you discount looking for specific headers that it's reasonable to have or gate off by preprocessor-chosen platforms (like...we probably don't _actually_ have to check for HAVE_STDIO_H, etc).

The deeper problem is this: SDL2 might be using X11, but we do not know this at configure time for sdl12-compat (and, as Wayland matures, we don't know this at _runtime_ either!), so things using SDL_syswm for direct X11 access are increasingly going to fail to function no matter what we do. In such a case (and since we don't actually provide this interface yet in sdl12-compat), it might make sense to dump the X11 includes entirely.

Just thinking out loud here, I don't know if any of this is a good idea yet.

**Comment by slouken** [comment]
I think we should try to ensure that SDL 1.2 games that rely on X11 continue to function under X11. Obviously they won't work under wayland, but we should make the syswm interfaces and events work on platforms that continue to make sense. (e.g. X11, windows, etc.)

**Comment by icculus** [comment]
As of b5715546c0a995d69cbdaffe663adbeb9a2228c2, we support the 1.2 syswm interfaces; they were only implemented for a few platforms in 1.2, and only Windows and X11 still exist in SDL2.

They work, as well as they can, if the user is still on these targets. There's not much we can do if it needs the X11 "full screen window" because that concept is gone in SDL2, but this should work if they just need to do some target-specific magic to a win32 HWND or the X11 Window.

I think it's good enough until we hear about a failing test case.

**Comment by slouken** [comment]
Yep, that sounds good.
