### ISSUE TITLE
Renderer without SDL_RENDERER_PRESENTVSYNC by default?

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#13]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-03-22 21:23:53 +0000, Dario wrote:

> In SDL_SetVideoMode, the SDL20_CreateRenderer for non-OpenGL windows uses the SDL_RENDER_PRESENTVSYNC by default.
> 
> This limits the FPS of a game to my monitor refresh rate, which does not happen with SDL 1.2
> 
> According to https://discourse.libsdl.org/t/vsync/8855 VSYNC was not enabled by default on SDL 1.2.

**Comment by icculus** [comment]
Oh, one note: if your app is using SDL_UpdateRect or SDL_UpdateRects and doesn't update the entire screen in a single rectangle, sdl12-compat will refuse to call SDL_RenderPresent at faster than ~60fps.

With software surfaces in 1.2, you could update just portions of the screen with UpdateRect, and they would present as fast as possible with just the dirty rects replaced. With GPU APIs, we have to redraw the whole thing every frame, so if sdl12-compat sees you doing dirty rectangles, it'll batch them and present once at a "reasonable" framerate.

OpenGL apps also don't have this problem, and software renderers that do one rectangle for the whole frame (or call SDL_Flip()), will also present as fast as possible, now that vsync is disabled by default. This is the best we can do.

(and, if you _want_ vsync because you don't like tearing or the game is running too fast, you can set the SDL12COMPAT_SYNC_TO_VBLANK=1 enviroment variable, and we'll use vsync.)
