### ISSUE TITLE
Psychonauts: Game crashes with resolution change.

### ISSUE THREAD

**Issue by Bitwolfies** [libsdl-org/sdl12-compat#156]
On Xorg (no idea about Wayland) these libraries will crash the game apon using the resolution option, what resolution does not matter, it will always crash.

**Comment by sulix** [comment]
Does the game actually crash, or does it just show a black screen?

I can reproduce a black screen here after changing resolution, which seems to be because the game doesn't handle the OpenGL context being destroyed/recreated properly. Specifically, it looks like Psychonauts tries to ``glUseProgram()`` a shader from the previous context. (Making sdl12-compat just keep the old context appears to fix the issue here — even under Wayland — but might break other things.)

**Comment by icculus** [comment]
> (Making sdl12-compat just keep the old context appears to fix the issue here — even under Wayland — but might break other things.)

But doesn't the real SDL 1.2 destroy the existing context during SDL_SetVideoMode...?

**Comment by icculus** [comment]
> But doesn't the real SDL 1.2 destroy the existing context during SDL_SetVideoMode...?

Oh my god, it doesn't.  😬

**Comment by icculus** [comment]
Okay, I'm not totally crazy...it _does_throw away the GL context during SDL_SetVideoMode on macOS in all cases...

https://github.com/libsdl-org/SDL-1.2/blob/main/src/video/quartz/SDL_QuartzVideo.m#L1238-L1243

But it doesn't appear to do so on x11 or win32, at least not in all cases. It might need to if going from fullscreen/windowed, or if you choose a different color depth, but I haven't dug that far.

In sdl12-compat--since I incorrectly believed SDL 1.2 did this on every platform--we intentionally destroy any existing GL context when calling SDL_SetVideoMode. We need to at least #ifdef this for macOS, if not remove it outright. And maybe retest a bunch of stuff.  :(

**Comment by slouken** [comment]
Dude...

**Comment by icculus** [comment]
macOS (Quartz backend) does this:

https://github.com/libsdl-org/SDL-1.2/blob/eeac82f364fd3ebd7bb78b118c6a6cc9ecb49bb3/src/video/quartz/SDL_QuartzVideo.m#L1238-L1243

- Destroy the existing GL context unconditionally.


X11 does this:

https://github.com/libsdl-org/SDL-1.2/blob/eeac82f364fd3ebd7bb78b118c6a6cc9ecb49bb3/src/video/x11/SDL_x11video.c#L1176-L1192

Keep the GL context if:
- Window exists
- is already SDL_OPENGL
- BitsPerPixel hasn't changed
- SDL_NOFRAME hasn't changed
- Doesn't care if window size _or fullscreen_ changes.


windib does this:

https://github.com/libsdl-org/SDL-1.2/blob/eeac82f364fd3ebd7bb78b118c6a6cc9ecb49bb3/src/video/windib/SDL_dibvideo.c#L607-L632

- Window exists
- _none_ of the flags (except SDL_ANYFORMAT) have changed
- is already SDL_OPENGL
- is _not_ a fullscreen window.


windx5 does this:

https://github.com/libsdl-org/SDL-1.2/blob/eeac82f364fd3ebd7bb78b118c6a6cc9ecb49bb3/src/video/windx5/SDL_dx5video.c#L1074-L1077

- Always destroy the GL context unconditionally.


What a mess.

**Comment by icculus** [comment]
I think I'm going to special-case this for X11, and unconditionally destroy existing GL contexts everywhere else. This probably isn't as large of a problem as I initially thought it was.

**Comment by icculus** [comment]
Wasn't hard to match the most important platforms, so I was more precise than originally planned.

This patch definitely fixes Psychonauts here.
