### ISSUE TITLE
Psychonauts: Anolog stick broken in menu.

### ISSUE THREAD

**Issue by Bitwolfies** [libsdl-org/sdl12-compat#157]
When using the compat, anolog stick movement in the menus no longer works, but its fine with the real binaries. The stick still can be used for movement however.

**Comment by sulix** [comment]
This works fine for me: joystick behaviour is exactly the same between SDL1.2 and sdl12-compat, with the analogue stick working fine in both. (The left analogue stick on my weird, knock-off PS2 controller works, the right one doesn't control the menu.)

What joystick/gamepad are you using, and does it work in other SDL2 games? Does setting ``SDL_JOYSTICK_HIDAPI=0`` help?

**Comment by icculus** [comment]
Actually, this brings up a good question, regardless of the problem here:

Do we want to add an option to expose SDL2 _game controllers_ as joysticks? They still look the same to the 1.2 app, but it guarantees that the button and axis ordering is reliable between devices.

**Comment by slouken** [comment]
> Actually, this brings up a good question, regardless of the problem here:
> 
> Do we want to add an option to expose SDL2 _game controllers_ as joysticks? They still look the same to the 1.2 app, but it guarantees that the button and axis ordering is reliable between devices.

Hmm, that's an interesting idea...

**Comment by icculus** [comment]
Ok, two changes in that patch worth mentioning:

- SDL 1.2 had no concept of joystick hotplug, so the initial device list was the final list, too...if something got unplugged, it would just fail to open, or stop sending new data, afaict. Now we also take a list at startup, open all the devices, and hold onto them in case the 1.2 app wants them, so the list can stay consistent. Previously, we'd just pass the device indices through to SDL2, but these aren't stable there.
- Now you can set a hint to use game controllers instead of joysticks, which might give you more control, since you get reliable axis/button ordering and can adjust it to make it work with whatever a game might need...not to mention dead zones, making hats look like buttons, etc.

My hope is that this can work around any Psychonauts issue, as it's probably an axis that doesn't sit at zero when idle (perhaps a trigger?) confusing things, and with game controllers, that won't be axis 0 and 1 anymore.

**Comment by icculus** [comment]
> My hope is that this can work around any Psychonauts issue

(And since there's not much else to do here, I'm closing the bug; we can reopen if anything new information pops up.)
