### ISSUE TITLE
SDL_GetWMInfo fails

### ISSUE THREAD

**Issue by jengelh** [libsdl-org/sdl12-compat#163]
```
#include <SDL/SDL_syswm.h>
#include <SDL/SDL.h>
int main()
{
        SDL_SysWMinfo info = {};
        Display *dpy;
        SDL_Init(SDL_INIT_VIDEO);
        if (SDL_GetWMInfo(&info)) {
                dpy = info.info.x11.display;
                printf("GetWMInfo succeeded, dpy is %p\n", dpy);
        } else {
                printf("GetWMInfo no success\n");
                dpy = nullptr;
        }
}
```

Observed output with SDL 1.2:

```
GetWMInfo succeeded, dpy is 0xeb7000
```

Observed with sdl12_compat 1.2.52:

```
GetWMInfo no success
```

Environment is a openSUSE Tumbleweed 20220303 amd64 with x11/xfce4.

```
$ xdpyinfo
name of display:    :0.0
version number:    11.0
vendor string:    The X.Org Foundation
vendor release number:    12101003
X.Org version: 1.21.1.3
```

**Comment by icculus** [comment]
Can reproduce here; the SDL_GetError is "Invalid window" because SDL2 wants a specific window here, but 1.2 will still work (and return a valid Display and null window inside the struct). sdl12-compat is passing the VideoWindow20--whatever the last SDL_SetVideoMode call produced--which is NULL in this program, which upsets SDL2.
