### ISSUE TITLE
sdl12_compat does not support antialiasing (ut2004)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#19]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-05-27 14:07:08 +0000, Tom B wrote:

> This compatibility tool works great for playing the game, but it is missing the ability to use antialiasing.
> 
> In SDL1.2 you can specify the following in UT2004.ini to get antialiasing:
> 
> [OpenGLDrv.OpenGLRenderDevice]
> MultisampleBuffers=1
> MultisampleSamples=8
> MultisampleHint=2
> 
> 
> When using sdl12_compat, antialiasing is no longer enabled.

**Comment by icculus** [comment]
The meaningful piece of this in UT2004 is this:

```c
SDL_GL_SetAttribute( SDL_GL_MULTISAMPLEBUFFERS, MultisampleBuffers );
SDL_GL_SetAttribute( SDL_GL_MULTISAMPLESAMPLES, MultisampleSamples );
```

This _should_ work in sdl12-compat, as this code appears to be hooked up, but I suspect UT2004 doesn't properly call this before creating the GL context or something. I'll have to dig deeper.

**Comment by icculus** [comment]
Ok, I just checked this and it's working correctly. Here's UT2004 with sdl12-compat, with MultisampleBuffers and MultisampleSamples set to zero...

![Screenshot from 2021-02-26 19-57-07](https://user-images.githubusercontent.com/673562/109370183-40de2200-786d-11eb-846a-2a9d6aaccce9.png)

...and here's it set to 1 and 16...

![Screenshot from 2021-02-26 19-54-50](https://user-images.githubusercontent.com/673562/109370203-54898880-786d-11eb-9362-7c2dc4651131.png)

...you can tell from the "THE WAY IT'S MEANT TO BE PLAYED" text and the edge of the white disc that one is clearly multisampled and the other isn't.

It's possible we fixed this since the bug report? Closing this bug.
