### ISSUE TITLE
Rendering failure with Closure

### ISSUE THREAD

**Issue by vv221** [libsdl-org/sdl12-compat#342]
I am trying to run the Humble Bundle native Linux build for Closure (https://www.humblebundle.com/store/closure), and while it runs fine using a real SDL 1.2 library (1.2.15 from Debian Bookworm) it fails to render anything but a black screen with sdl12-compat (1.2.68 from Debian Sid).

The music is playing in the background, so the game itself seems to run. But nothing is rendered beside the black screen.

## System details

- Debian Trixie/Sid
- sdl12-compat 1.2.68
- SDL 2.30.8

**Comment by sulix** [comment]
This seems to be another Cg game which breaks with OpenGL scaling.

It works fine with ``SDL12COMPAT_OPENGL_SCALING=0`` set, so I've added a quirk in #343.

I did try the hacked Cg stuff in [glx_wrapper](https://gist.github.com/sulix/fe951daaeb4e51dfb329e5935e705cbf), but it wasn't enough to get it working with OpenGL scaling (unlike, e.g., Braid), so I suspect there's something else going on, not just Cg, but since disabling OpenGL scaling works great here, there's no sense trying something more complicated anyway.

**Comment by vv221** [comment]
> It works fine with `SDL12COMPAT_OPENGL_SCALING=0` set, so I've added a quirk in #343.

Thanks for the workaround, it works nicely here while I wait for the next sdl12-compat release including this new quirk.

> I did try the hacked Cg stuff in glx_wrapper

This is the first time I read about this. This is a preload shim I could use instead of a real libCg.so library with some games?
