### ISSUE TITLE
High DPI

### ISSUE THREAD

**Issue by sjnewbury** [libsdl-org/sdl12-compat#59]
Doesn't it make sense to set "SDL_WINDOW_ALLOW_HIGHDPI" in flags20 since the output is automatically rescaled anyway?  I patched sdl12-compat to unconditionally set it and tried it with UT2004 and it works well on Sway @3840x2160 2x scaled.

**Comment by icculus** [comment]
Yeah, but we probably need an environment variable to force it off if someone wants less pixels for more performance.

**Comment by flibitijibibo** [comment]
FWIW I ran into this in implementing high-DPI support in FNA - the end result was that we defaulted to having it _off_ and using the environment variable to turn it on:

https://github.com/FNA-XNA/FNA/wiki/7:-FNA-Environment-Variables#fna_graphics_enable_highdpi

There were two reasons for this:

- The XNA API did not anticipate high-DPI drawables, similar to SDL 1.2. Also vaguely similar to SDL 1.2 is that the window size is based on the backbuffer size, the latter being what the programmer sets - XNA has PreferredBackbufferWidth/Height, SDL has SetVideoMode. Both have sets and neither have gets (necessarily, you can dig in and get the info but it digs into uncharted territory), and conveniently it doesn't _strictly_ say the video mode is the window size. We ultimately decided that the backbuffer size should get priority over the window size; when FNA HighDPI is on we actually _shrink the window_ so that the video mode _technically_ matches what the program requested, at the expense of the window being small. This sounds weird until you consider that A: Many games are picky about the viewport size and would actually break if we made the backbuffer bigger than what they expected, and B: Consider the fullscreen scenario, where the game will request full 4K but the desktop's simulated size will be 1920x1080, so while the game thinks it's running a huge window it's actually just conforming to exactly how high-DPI works, with no weird application hacks required!
- For low-res games, defaulting to high-DPI is actually a problem! A good test case for this is VVVVVV; right now it defaults to always trying high-DPI, but the problem is that the default backbuffer size is _320x240_, and since we prioritize backbuffer size over window size...

![image](https://user-images.githubusercontent.com/1396814/120090613-e6ee3200-c0d1-11eb-9775-83984147ea7b.png)

It's a default setting for ants, but also a very likely default for old games using SDL 1.2! I've sort of looked the other way on this in VVV because I want to make fullscreen the default, which will make this unnoticeable 99% of the time, but it's still really funny when you first load it and a postage stamp suddenly pops up on your monitor.

This is probably way more text than was necessary, but I've worked on supporting this a lot so this is probably the exact one thing that I can actually contribute to 12-compat beyond just throwing old games at it. For a live example, load up FEZ for macOS or Wayland and enable the high-DPI mode in the video options menu.

**Comment by icculus** [comment]
I stuck a thing in there (defaulting to OFF).  Good enough, everyone?

**Comment by flibitijibibo** [comment]
lgtm!
