### ISSUE TITLE
lbreakout2 - no menu

### ISSUE THREAD

**Issue by sjnewbury** [libsdl-org/sdl12-compat#60]
lbreakout2 doesn't render the menu on the start screen.  The menu works if you click blindly and the game works fine.  It breifly appears when you quit the game.

**Comment by icculus** [comment]
I'll test this tonight, but in case you get there first: a bunch of surface blending fixes went in today, and likely fix this, too.

**Comment by icculus** [comment]
Nope, just tried and it's still broken. I'll track this down.

**Comment by icculus** [comment]
Ok, this happens because sdl12-compat is trying to coalesce dirty rectangle updates into a single rendered frame.

What sdl12-compat does is sees SDL_UpdateRects() called, and if it doesn't update the entire screen, it holds off on rendering until the next call to SDL_PumpEvents(), with the theory that if the app has moved on to event handling, then all the rendering is complete for this cycle and we can render a single frame.

The problem is that lbreakout2 appears to render it's whole frame, call SDL_UpdateRects(), clear parts of the screen surface for next time, and _then_ run its event loop, so sdl12-compat's heuristic fails in this case.

I guess I'll try updating the texture during UpdateRects, which I was avoiding for efficiency reasons, but should solve this. It's either that or keep a second copy of the software surface internally.  :/

**Comment by icculus** [comment]
Ok, this seems to work, and doesn't cause any regressions in my current test suite so far. I'm actually pretty happy with how this turned out, seems a little less hacky now.
