### ISSUE TITLE
testpalette.c issues...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl12-compat#63]
Now that the test apps build, we can see some problems in them.

testpalette looks incorrect, like this:

![2021-05-24_13-00](https://user-images.githubusercontent.com/673562/119382572-3545a000-bc90-11eb-8207-d027ae295889.png)

...and when you hit ESC to quit, on return from main(), it detects stack corruption and aborts.

**Comment by sulix** [comment]
So, this crashes on startup on my machine, similarly with memory corruption.

The issue seems to be that in SDL 2.0, the 'boat' surface loaded by ``SDL_LoadBMP()`` has a palette with 256 colours, whereas with SDL 1.2, it only has 66.

This appears to be because SDL 2.0 will ignore the biClrUsed field in favour of ``1 << biBitCount``, as "some bitmaps can bring wrong information for colorsUsed".

A "fix" for SDL2 exists [here](https://github.com/sulix/SDL/commit/a7abd7f5ea10d7b8a64b63fd33d49c3128904a76) — basically just undoing the "fix" for the issue above — but it seems that either way something will break. Maybe the correct fix here is to have a separate ``SDL_LoadBMP`` implementation for sdl12-compat?

Note that, even after this is fixed, ``testpalette`` still requires support for the SDL 1.2 physical palette, else the waves won't animate. I tried hacking together a quick implementation of it [here](https://github.com/sulix/sdl12-compat/commit/0d9287839c7e4a6bc97a50ff0864c73d16a2674a), and it seems to work, though it hasn't been tested more widely.

**Comment by sezero** [comment]
> The issue seems to be that in SDL 2.0, the 'boat' surface loaded by `SDL_LoadBMP()` has a palette with 256 colours, whereas with SDL 1.2, it only has 66.
> 
> This appears to be because SDL 2.0 will ignore the biClrUsed field in favour of `1 << biBitCount`, as "some bitmaps can bring wrong information for colorsUsed".
> 
> A "fix" for SDL2 exists [here](https://github.com/sulix/SDL/commit/a7abd7f5ea10d7b8a64b63fd33d49c3128904a76) — basically just undoing the "fix" for the issue above

Did you submit this to SDL? It may need discussing.

**Comment by sulix** [comment]
> > A "fix" for SDL2 exists [here](https://github.com/sulix/SDL/commit/a7abd7f5ea10d7b8a64b63fd33d49c3128904a76) — basically just undoing the "fix" for the issue above
> 
> Did you submit this to SDL? It may need discussing.

I haven't — I just linked to a branch to illustrate the problem. I definitely agree that it shouldn't go in without some discussion, as there's a distinct possibility it'll break someone's usecase if they have bitmaps that need this workaround. If we somehow can know for sure that no-one would get broken by it, it's a nice fix, but it's more likely that the right thing to do is to give sdl12-compat its own copy of ``SDL_LoadBMP_RW()`` which has this fix.

**Comment by icculus** [comment]
I'll take a look at the bmp code in SDL.

**Comment by icculus** [comment]
The physical palette fix looks good--you beat me to the same approach I was working on.  :)

It needs a few error checks added, but otherwise I think it's the right approach. I suspect it's also going to fix our lincity-ng rendering issues too. I'll confirm that today.

**Comment by icculus** [comment]
Ok, physical palette stuff is in. David's work in 6c7eba114e51779dd8562f5834829f2ee591934e and two tweaks from me in 0042f2c040d5144906a151b1c7185d302b887e3e and 8792c2f7c66ff01037673903870c5029e9955f5a.

Dealing with the bmp loader next.

**Comment by icculus** [comment]
That bmp "fix" has been in SDL_image for _17 years_.  😬

**Comment by icculus** [comment]
Changed this in SDL: https://github.com/libsdl-org/SDL/commit/fed846508577419ec0bacb6d1bbbb9074c83c65f

I think this resolves this bug?

(lincity-ng wasn't affected by this, so that's either an alpha blending or colorkey issue. So ignore that for this bug report.)

**Comment by sezero** [comment]
> Changed this in SDL: [libsdl-org/SDL@fed8465](https://github.com/libsdl-org/SDL/commit/fed846508577419ec0bacb6d1bbbb9074c83c65f)
> 
> I think this resolves this bug?

It possibly resolves it in SDL itself (didn't really test). However: Unless we
require SDL >= 2.0.16 in sdl12-compat, the issue still stays here.

**Comment by icculus** [comment]
I don't think we should paste the entire bmp loader into sdl12-compat to fix one corner case in a test program.

SDL2 before today still works for almost all cases and when people upgrade it will work for all of them. I think it's okay as it is.
